<?php

namespace App\Repositories;

use App\Models\Customers;
use Illuminate\Support\Facades\Auth;
use Kizi\Core\Repositories\BaseRepository;

class CustomerRepository extends BaseRepository
{
    public function model()
    {
        return Customers::class;
    }

    public function getList($params)
    {
        $query = $this->model;
        if (Auth::check()) {
            $query = $query->where('id', '<>', Auth::user()->id);
        }
        $result = $this->paging(
            $query,
            $params
        );
        return $result;
    }

    protected function beforeSave(array &$attributes)
    {
        parent::beforeSave($attributes); // TODO: Change the autogenerated stub
        if (!empty($attributes['password']) && $attributes['password'] != '' && $attributes['password'] != null) {
            $attributes['password'] = bcrypt($attributes['password']);
        }
    }
}
