<?php

namespace App\Http\Controllers;

use App\Repositories\PropertyRepository;
use Kizi\Core\Http\Controllers\Controller;

class PropertyController extends Controller
{
    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }
    protected function validateStore()
    {
        $this->validation(
            [
                'name'    => [
                    'required',
                ],
                'area'    => [
                    'required',
                ],
                'type'    => [
                    'required',
                    'in:buy,rent'
                ],
                'price'    => [
                    'required',
                    'integer'
                ],
                'is_active'    => [
                    'boolean',
                ],
                'province_id'    => [
                    'required',
                ],
                'content'    => [
                    'required',
                ],
            ]
        );
        parent::validateStore(); // TODO: Change the autogenerated stub
    }
}
