<?php

namespace Kizi\Core\Http\Controllers;


use Illuminate\Http\Response;
use Kizi\Core\Models\Settings;

class SettingController extends Controller
{
    public function index()
    {
        return response_api(setting());
    }

    public function store()
    {
        Settings::setMany(request()->all());
        return response_api(
            setting(),
            Response::HTTP_OK,
            __('core.actions.create_success')
        );
        return parent::store(); // TODO: Change the autogenerated stub
    }
//    public $validation = ContactRequest::class;
}
