<?php

namespace Kizi\Core\Http\Controllers;


use Kizi\Core\Contracts\Repositories\UserRepository;

class UserController extends Controller
{
    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;
    }

    protected function validateStore()
    {
        $this->validation(
            [
                'email'                 => [
                    'required',
                    'email',
                    'max:191',
                    'unique:users',
                ],
                'password'              => [
                    'required',
                    'min:6',
                    'max:20',
                ],
                'password_confirmation' => [
                    'required_with:password',
                    'min:6',
                    'max:20',
                    'same:password',
                ],
                'is_active'             => [
                    'required',
                    'boolean',
                ],
            ]
        );
        parent::validateStore(); // TODO: Change the autogenerated stub
    }

    protected function validateUpdate($id)
    {
        $this->validation(
            [
                'email'                 => [
                    'email',
                    'max:191',
                    'unique:users,email,'.$id.',id',
                ],
                'password'              => [
                    'min:6',
                    'max:20',
                ],
                'password_confirmation' => [
                    'required_with:password',
                    'min:6',
                    'max:20',
                    'same:password',
                ],
                'is_active'             => [
                    'boolean',
                ],
            ]
        );
        parent::validateUpdate($id); // TODO: Change the autogenerated stub
    }
}
