<?php
/**
 * Created by PhpStorm.
 * User: nhockizi
 * Date: 11/17/21
 * Time: 13:38
 */

namespace App\Services;


class UserService extends \Kizi\Core\Services\UserService
{
//    public function login($request)
//    {
//        $role = $request->header('App-Role') ?? null;
//        switch ($role) {
//            case 'admin':
//                dd(1);
//                break;
//            default:
//                return parent::login($request);
//                break;
//        }
//         // TODO: Change the autogenerated stub
//    }
}