<?php
/**
 * Created by PhpStorm.
 * User: nhockizi
 * Date: 11/17/21
 * Time: 13:38
 */

namespace App\Services;


class UserService extends \Kizi\Core\Services\UserService
{
    public function login($request)
    {
        dd(1);
        return parent::login($request); // TODO: Change the autogenerated stub
    }
}